---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: dev
spec:
  interval: 1m0s
  path: ./deploy/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  patchesJson6902:
  - target:
      version: apps/v1
      kind: Deployment
      name: backend
    patch:
    - op: add
      path: "/metadata/labels/app.kubernetes.io~1instance"
      value: podinfo
